# Generated by Django 3.0.6 on 2020-05-26 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_image_path)),
                ('description', models.CharField(max_length=300)),
                ('website', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSoftSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Advanced'), ('3', 'Expert')], max_length=10)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Softskill')),
            ],
            options={
                'unique_together': {('candidate', 'skill')},
                'index_together': {('candidate', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='CandidateHardSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Advanced'), ('3', 'Expert')], max_length=10)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Hardskill')),
            ],
            options={
                'unique_together': {('candidate', 'skill')},
                'index_together': {('candidate', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='hardskills',
            field=models.ManyToManyField(through='profiles.CandidateHardSkill', to='jobs.Hardskill'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Type'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='softskills',
            field=models.ManyToManyField(through='profiles.CandidateSoftSkill', to='jobs.Softskill'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='tasks',
            field=models.ManyToManyField(to='jobs.Task'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
