# Generated by Django 3.0.6 on 2020-05-26 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200526_1349'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatehardskill',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_to_skill', to='profiles.Candidate'),
        ),
        migrations.AlterField(
            model_name='candidatehardskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_to_candidate', to='jobs.Hardskill'),
        ),
    ]
