# Generated by Django 3.0.5 on 2020-04-16 09:36

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200416_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_image_path),
        ),
    ]
