# Generated by Django 3.0.6 on 2020-05-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_company'),
        ('profiles', '0005_auto_20200416_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='tasks',
            field=models.ManyToManyField(to='jobs.Task'),
        ),
        migrations.CreateModel(
            name='CandidateSoftSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Advanced'), ('3', 'Expert')], max_length=10)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Softskill')),
            ],
            options={
                'unique_together': {('candidate', 'skill')},
                'index_together': {('candidate', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='CandidateHardSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Advanced'), ('3', 'Expert')], max_length=10)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Hardskill')),
            ],
            options={
                'unique_together': {('candidate', 'skill')},
                'index_together': {('candidate', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='hardskills',
            field=models.ManyToManyField(through='profiles.CandidateHardSkill', to='jobs.Hardskill'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='softskills',
            field=models.ManyToManyField(through='profiles.CandidateSoftSkill', to='jobs.Softskill'),
        ),
    ]
