# Generated by Django 3.0.6 on 2020-05-23 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_auto_20200523_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=profiles.models.upload_image_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
