# Generated by Django 3.0.6 on 2020-05-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200523_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='avatar',
        ),
    ]
