# Generated by Django 3.0.6 on 2020-05-23 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_auto_20200416_0936'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Hardskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('level', models.CharField(choices=[('1', 'Junior'), ('2', 'Advanced'), ('3', 'Senior')], max_length=10, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Softskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('1', 'Soft Skill'), ('2', 'Technical Skill')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSoftSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Advanced'), ('3', 'Expert')], max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Softskill')),
            ],
            options={
                'unique_together': {('profile', 'skill')},
                'index_together': {('profile', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='ProfileHardSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Advanced'), ('3', 'Expert')], max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Hardskill')),
            ],
            options={
                'unique_together': {('profile', 'skill')},
                'index_together': {('profile', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='hardskills',
            field=models.ManyToManyField(through='jobs.ProfileHardSkill', to='jobs.Hardskill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='offers',
            field=models.ManyToManyField(to='jobs.Offer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='softskills',
            field=models.ManyToManyField(through='jobs.ProfileSoftSkill', to='jobs.Softskill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tasks',
            field=models.ManyToManyField(to='jobs.Task'),
        ),
        migrations.CreateModel(
            name='JobSoftSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Advanced'), ('3', 'Expert')], max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Softskill')),
            ],
            options={
                'unique_together': {('job', 'skill')},
                'index_together': {('job', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='JobHardSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Advanced'), ('3', 'Expert')], max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Hardskill')),
            ],
            options={
                'unique_together': {('job', 'skill')},
                'index_together': {('job', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='hardskills',
            field=models.ManyToManyField(through='jobs.JobHardSkill', to='jobs.Hardskill'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='offers',
            field=models.ManyToManyField(to='jobs.Offer'),
        ),
        migrations.AddField(
            model_name='job',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Profile'),
        ),
        migrations.AddField(
            model_name='job',
            name='softskills',
            field=models.ManyToManyField(through='jobs.JobSoftSkill', to='jobs.Softskill'),
        ),
        migrations.AddField(
            model_name='job',
            name='tasks',
            field=models.ManyToManyField(to='jobs.Task'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobs.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
                'index_together': {('user', 'job')},
            },
        ),
    ]
