# Generated by Django 3.0.6 on 2020-05-26 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Company'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='hardskills',
            field=models.ManyToManyField(through='jobs.JobHardSkill', to='jobs.Hardskill'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='offers',
            field=models.ManyToManyField(to='jobs.Offer'),
        ),
        migrations.AddField(
            model_name='job',
            name='softskills',
            field=models.ManyToManyField(through='jobs.JobSoftSkill', to='jobs.Softskill'),
        ),
        migrations.AddField(
            model_name='job',
            name='tasks',
            field=models.ManyToManyField(to='jobs.Task'),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Type'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='typesoftskill',
            unique_together={('type', 'skill')},
        ),
        migrations.AlterIndexTogether(
            name='typesoftskill',
            index_together={('type', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='typehardskill',
            unique_together={('type', 'skill')},
        ),
        migrations.AlterIndexTogether(
            name='typehardskill',
            index_together={('type', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='jobsoftskill',
            unique_together={('job', 'skill')},
        ),
        migrations.AlterIndexTogether(
            name='jobsoftskill',
            index_together={('job', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='jobhardskill',
            unique_together={('job', 'skill')},
        ),
        migrations.AlterIndexTogether(
            name='jobhardskill',
            index_together={('job', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('user', 'job')},
        ),
        migrations.AlterIndexTogether(
            name='applicant',
            index_together={('user', 'job')},
        ),
    ]
