# Generated by Django 3.0.6 on 2020-05-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skillship',
            unique_together={('job', 'skill')},
        ),
        migrations.AlterIndexTogether(
            name='skillship',
            index_together={('job', 'skill')},
        ),
    ]
