# Generated by Django 3.0.6 on 2020-05-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
    ]
