# Generated by Django 3.0.5 on 2020-04-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('1', 'Soft Skill'), ('2', 'Technical Skill')], max_length=10)),
            ],
        ),
    ]
