# Generated by Django 3.0.6 on 2020-05-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_delete_profiletask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Softskill',
        ),
    ]
