# Generated by Django 3.0.6 on 2020-05-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200521_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Title'),
        ),
    ]
