# Generated by Django 3.0.6 on 2020-05-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200526_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='type',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
