# Generated by Django 3.0.6 on 2020-05-22 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200522_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileHardSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Advanced'), ('3', 'Expert')], max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Hardskill')),
            ],
            options={
                'unique_together': {('profile', 'skill')},
                'index_together': {('profile', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='hardskills',
            field=models.ManyToManyField(through='jobs.ProfileHardSkill', to='jobs.Hardskill'),
        ),
    ]
