# Generated by Django 3.0.6 on 2020-05-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='created_by',
        ),
    ]
