# Generated by Django 3.0.5 on 2020-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, to='jobs.Skill'),
        ),
    ]
