# Generated by Django 3.0.6 on 2020-05-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_profile_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='category',
            new_name='Category',
        ),
    ]
