# Generated by Django 3.0.6 on 2020-05-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200522_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Category',
            new_name='category',
        ),
    ]
