# Generated by Django 3.0.6 on 2020-05-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200528_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskill',
            name='dependency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Hardskill'),
        ),
    ]
