# Generated by Django 3.0.6 on 2020-05-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_hardskill_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskill',
            name='dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Hardskill'),
        ),
    ]
