# Generated by Django 3.0.6 on 2020-05-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='created_by',
            new_name='user',
        ),
    ]
