# Generated by Django 3.0.6 on 2020-05-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200528_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardskill',
            name='description',
        ),
    ]
