# Generated by Django 3.0.6 on 2020-05-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20200524_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='created_by',
        ),
    ]
