# Generated by Django 3.0.6 on 2020-06-03 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0008_remove_hardskill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhardskill',
            name='relevanz',
            field=models.CharField(choices=[('1', 'Must-have'), ('2', 'Nice-to-Have')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
