# Generated by Django 3.0.6 on 2020-06-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20200603_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobhardskill',
            name='level',
        ),
    ]
