# Generated by Django 3.0.6 on 2020-06-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_jobhardskill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='level',
        ),
    ]
