# Generated by Django 3.0.6 on 2020-06-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_type_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='typehardskill',
            name='relevanz',
            field=models.CharField(choices=[('1', 'Must-have'), ('2', 'Nice-to-Have')], max_length=10, null=True),
        ),
    ]
