# Generated by Django 3.0.6 on 2020-06-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_typehardskill_relevanz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typehardskill',
            name='level',
        ),
    ]
