# Generated by Django 3.0.6 on 2020-06-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_remove_typehardskill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
