# Generated by Django 3.0.6 on 2020-06-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
    ]
