# Generated by Django 3.0.6 on 2020-06-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20200604_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salarymax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salarymin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
