# Generated by Django 3.0.6 on 2020-06-11 07:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20200611_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tasks',
        ),
        migrations.AddField(
            model_name='job',
            name='tasks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), null=True, size=None),
        ),
    ]
