# Generated by Django 3.0.6 on 2020-06-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20200611_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tasks',
        ),
    ]
