# Generated by Django 3.0.6 on 2020-06-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_job_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='offers',
        ),
    ]
