# Generated by Django 3.0.6 on 2020-06-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.Education'),
            preserve_default=False,
        ),
    ]
