# Generated by Django 3.0.6 on 2020-06-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_job_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Experience')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Type')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.ManyToManyField(through='jobs.JobExperience', to='jobs.Experience'),
        ),
    ]
