# Generated by Django 3.0.6 on 2020-06-11 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_auto_20200611_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='JobLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Business'), ('2', 'Advanced'), ('3', 'Native')], max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Language')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.ManyToManyField(through='jobs.JobLanguage', to='jobs.Language'),
        ),
    ]
