# Generated by Django 3.0.6 on 2020-06-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_auto_20200611_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='salarymax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='salarymin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
