# Generated by Django 3.0.6 on 2020-06-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_auto_20200611_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='experience',
        ),
        migrations.DeleteModel(
            name='TypeExperience',
        ),
    ]
