# Generated by Django 3.0.6 on 2020-06-11 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_auto_20200611_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Experience')),
                ('from_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_type', to='jobs.Type')),
                ('to_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_type', to='jobs.Type')),
            ],
        ),
        migrations.AddField(
            model_name='type',
            name='experience',
            field=models.ManyToManyField(through='jobs.TypeExperience', to='jobs.Type'),
        ),
    ]
