# Generated by Django 3.0.6 on 2020-06-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_auto_20200611_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Business'), ('2', 'Advanced'), ('3', 'Native')], max_length=10)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Language')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Type')),
            ],
        ),
        migrations.AddField(
            model_name='type',
            name='language',
            field=models.ManyToManyField(through='jobs.TypeLanguage', to='jobs.Language'),
        ),
    ]
