# Generated by Django 3.0.6 on 2020-06-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_auto_20200611_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='created_at',
        ),
    ]
