# Generated by Django 3.0.6 on 2020-06-20 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0035_auto_20200611_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='types', to=settings.AUTH_USER_MODEL),
        ),
    ]
