# Generated by Django 3.0.6 on 2020-07-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0038_auto_20200621_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='experience',
            new_name='type_experience',
        ),
    ]
