# Generated by Django 3.0.6 on 2020-07-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_auto_20200708_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type_experience',
            new_name='experience',
        ),
    ]
