version: '3'

services:
  db:
    image: postgres
    # ports: 
    #   - 5432:5432
    expose:
      - 5432
    environment:
      # - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=djangojobportal
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db